# Define your repository and credential
imagePullSecret: secret-registry


replicaCount: 1

image:
  name: 541407012130.dkr.ecr.us-east-1.amazonaws.com/REPLACE_APP_NAME:REPLACE_IMAGE_HASH
  pullPolicy: Always


# Container  Port
ports:
  enabled: true
  containerPort: 8080

# Service controlls
service:
  enabled: true
  type: ClusterIP
  port: 80

# Default Container Termination Time
terminationGracePeriodSeconds: 30

#Health Checks
resources:
  enabled: true
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    cpu: 25m
    memory: 256Mi


readinessProbe:
  enabled: true
  httpGet:
    path: /api/actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 1
  successThreshold: 1

livenessProbe:
  enabled: true
  httpGet:
    path: /api/actuator/health 
    port: 8080
  initialDelaySeconds: 70
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 1
  successThreshold: 1
