spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://new-app-mpay-proddb.cijqkywi5gr7.us-east-1.rds.amazonaws.com:5432/msuberdb}
    username: ${DB_USERNAME:msuber}
    password: ${DB_PASSWORD:msuber}

springdoc:
  hostname: https://uber.mpay.az

schedule:
  fixed-delay:
    in:
      milliseconds: 600000

mpay:
  url: https://app.mpay.az
  token: 3qeca64qnnq0cu3r2o6e2aotbi
  gate-serial: 316921934191
  gate-token: ne7gnhrp79f3lrkcnk0s3hvbv0
  park-token: 3mhlf1m9mtf31r3faveo208alp
  bank-details:
    bic: RBTAAZ22
