spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://172.23.38.99:5432/ms_uber_db}
    username: ${DB_USERNAME:msuber}
    password: ${DB_PASSWORD:msuber}

springdoc:
  hostname: https://sb-uber.mpay.az

schedule:
  cron:
    expression: 0 */5 * * * *

  fixed-delay:
    in:
      milliseconds: 600000
