 server:
   port: 8081

spring:
  profiles:
    active: local

  datasource:
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/ms_unitech_db}
#    username: ${DB_USERNAME:msunitech}
#    password: ${DB_PASSWORD:msunitech}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        enable_lazy_load_no_trans: true

    open-in-view: false

  jackson:
    serialization:
      fail-on-empty-beans: false

  application:
    name: ms-unitech

springdoc:
  packagesToScan: az.mpay.unitech.controller
#  paths-to-match: /api/**
  hostname: http://localhost:8081

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health
