apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
    - host: uber.mpay.az
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
            path: /
